#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = `pkg-config --cflags opencv` -Wall -fexceptions -std=c++11
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = `pkg-config --libs opencv`

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/forestry

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/forestry

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/src/Cell.o $(OBJDIR_DEBUG)/src/SimulationDriver.o $(OBJDIR_DEBUG)/src/World.o $(OBJDIR_DEBUG)/src/Display.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/src/Cell.o $(OBJDIR_RELEASE)/src/SimulationDriver.o $(OBJDIR_RELEASE)/src/World.o $(OBJDIR_RELEASE)/src/Display.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/src/Cell.o: src/Cell.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Cell.cpp -o $(OBJDIR_DEBUG)/src/Cell.o

$(OBJDIR_DEBUG)/src/SimulationDriver.o: src/SimulationDriver.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SimulationDriver.cpp -o $(OBJDIR_DEBUG)/src/SimulationDriver.o

$(OBJDIR_DEBUG)/src/World.o: src/World.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/World.cpp -o $(OBJDIR_DEBUG)/src/World.o

$(OBJDIR_DEBUG)/src/Display.o: src/Display.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Display.cpp -o $(OBJDIR_DEBUG)/src/Display.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/src/Cell.o: src/Cell.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Cell.cpp -o $(OBJDIR_RELEASE)/src/Cell.o

$(OBJDIR_RELEASE)/src/SimulationDriver.o: src/SimulationDriver.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SimulationDriver.cpp -o $(OBJDIR_RELEASE)/src/SimulationDriver.o

$(OBJDIR_RELEASE)/src/World.o: src/World.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/World.cpp -o $(OBJDIR_RELEASE)/src/World.o

$(OBJDIR_RELEASE)/src/Display.o: src/Display.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Display.cpp -o $(OBJDIR_RELEASE)/src/Display.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

